version: '3.5'
services:
  broker:
    image: confluentinc/cp-kafka:latest
    volumes:
      - ./kafka-properties/server.properties:/etc/kafka/server.properties
      - ./kafka-data:/var/lib/kafka/data
    ports:
      - "9092:9092"
    entrypoint: >
      sh -c 'if [ ! -f /var/lib/kafka/data/meta.properties ]; then
        export CLUSTER_ID=$(kafka-storage random-uuid) &&
        kafka-storage format --ignore-formatted --cluster-id "$CLUSTER_ID" --config /etc/kafka/server.properties;
      fi &&
      kafka-server-start /etc/kafka/server.properties'
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - "8082:8080"